# BEGIN_KITTY_FONTS
font_family      family="ProFontWindows Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16.0
# END_KITTY_FONTS

# BEGIN_CONFIGS
enable_audio_bell no
visual_bell_duration 0.0
shell_integration enabled
cursor_shape block

confirm_os_window_close 0
copy_on_select clipboard

tab_bar_style powerline
tab_powerline_style slanted
# END_CONFIGS

# BEGIN_INCLUDES
# include themes/dracula.conf
# include themes/Spacedust.conf
include themes/Xcodedark.conf
# END_INCLUDES
